Bugfix: reference 'rxjs-imports'
File `rxjs-imports.ts` is not referenced anywhere which causes the application fail to start:
```
Uncaught TypeError: action$.ofType(...).concatMap is not a function...
```